In [ ]:
# Import Libraries

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/cleane_used cars.csv")

In [ ]:
df.head()

,Car_ID,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner,Engine_CC,Mileage_kmpl,Price_INR,City
0,1,2,12,2016,69196,2,1,1,1598.0,23.3,1293716,3
1,4,5,19,2011,29312,1,1,3,1998.0,16.2,704740,3
2,6,4,19,2010,66024,2,0,3,1497.0,21.4,915108,0
3,7,3,21,2014,180682,1,1,2,1498.0,23.1,492679,4
4,8,6,15,2015,184467,1,1,2,1998.0,10.6,811552,4

In [ ]:
# divide Dependent & Independent Variable

X = df.drop('Price_INR', axis=1)

y = df['Price_INR']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,root_mean_squared_error

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Make Predictions

y_pred = model.predict(X_test)

In [ ]:
mae = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

print("MAE:",mae)

print("r2:",r2)

print("RMSE:",mse)

MAE: 211829860979.6151
r2: -0.08460264846610066
RMSE: 211829860979.6151

In [ ]:
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

results.head(10)

      Actual     Predicted
139  1124384  1.193860e+06
30    914729  8.796666e+05
119  1248829  1.038321e+06
29   1599173  1.001321e+06
144   217916  1.065822e+06
163  1108374  9.076858e+05
166   657923  1.013928e+06
51    945085  9.601987e+05
105  1644013  8.832184e+05
60    793035  8.074441e+05